apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-backend-config
data:
  # Production environment specific settings
  LLM_PROVIDER: "azure_openai"
  AZURE_OPENAI_ENDPOINT: "https://prod-resource.openai.azure.com/"
  AZURE_OPENAI_DEPLOYMENT_NAME: "prod-gpt-4"
  AZURE_OPENAI_API_VERSION: "2024-12-01-preview"
  
  # Production database settings
  DATABASE_HOST: "prod-postgres-service"
  DATABASE_NAME: "chat_db_prod"
  
  # Production Redis settings
  REDIS_HOST: "prod-redis-service"
