apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ai-backend-production

# Base configuration 참조
resources:
  - ../../

# Namespace 설정
namespace: production

# 프로덕션 환경용 라벨 추가
commonLabels:
  environment: production
  tier: prod

# 프로덕션 환경용 설정
patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

# 이미지 태그 설정 (프로덕션은 특정 버전)
images:
  - name: ai-backend
    newTag: v1.0.0

# 레플리카 수 (프로덕션은 더 많이)
replicas:
  - name: ai-backend-deployment
    count: 3

# 프로덕션 환경용 ConfigMap 생성
configMapGenerator:
  - name: ai-backend-config-prod
    literals:
      - APP_DEBUG=false
      - APP_LOG_LEVEL=info
      - SERVER_RELOAD=false
      - LOG_TO_FILE=false
