apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
  namespace: prefect-system
  labels:
    app: prefect-server
    stage: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  template:
    metadata:
      labels:
        app: prefect-server
        stage: "1"
    spec:
      containers:
      - name: prefect-server
        image: prefecthq/prefect:2-latest
        command: ["prefect", "server", "start"]
        ports:
        - containerPort: 4200
          name: api
        - containerPort: 4201
          name: ui
        env:
        - name: PREFECT_DISABLE_TELEMETRY
          valueFrom:
            configMapKeyRef:
              name: prefect-config
              key: PREFECT_DISABLE_TELEMETRY
        - name: PREFECT_API_URL
          value: "http://0.0.0.0:4200/api"
        - name: PREFECT_UI_API_URL
          value: "http://0.0.0.0:4200/api"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: prefect-system
  labels:
    app: prefect-server
spec:
  selector:
    app: prefect-server
  ports:
  - name: api
    port: 4200
    targetPort: 4200
  - name: ui
    port: 4201
    targetPort: 4201
  type: ClusterIP 