apiVersion: v1
kind: ConfigMap
metadata:
  name: prefect-config
  namespace: prefect-system
data:
  # Prefect 설정
  PREFECT_DISABLE_TELEMETRY: "1"
  PREFECT_API_URL: "http://prefect-server:4200/api"
  
  # Azure OpenAI 설정 - 실제 값을 여기에 설정하세요
  AZURE_OPENAI_ENDPOINT: ""
  AZURE_OPENAI_API_VERSION: ""
  AZURE_OPENAI_DEPLOYMENT_NAME: ""
  AZURE_OPENAI_EMBEDDING_API_VERSION: ""
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT: ""
  
  # Azure AI Search 설정 - 실제 값을 여기에 설정하세요
  AZURE_SEARCH_ENDPOINT: ""
  AZURE_SEARCH_INDEX_NAME: ""
  
  # Milvus Lite 설정 (파일 기반)
  MILVUS_COLLECTION_NAME: "document_vectors"
  
  # PostgreSQL 설정 (K8s에서는 서비스명 사용)
  DATABASE_HOST: "postgresql-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "chat_db"
  DATABASE_USERNAME: "postgres"
  DATABASE_ECHO: "false"
  
  # 검색 설정
  SEARCH_COMBINED: "true"
  SEARCH_TEXT_ONLY: "true"
  SEARCH_IMAGE_ONLY: "true"
  SEARCH_HYBRID: "true"
  
  # 하이브리드 검색 가중치
  HYBRID_TEXT_WEIGHT: "0.6"
  HYBRID_IMAGE_WEIGHT: "0.4"
  
  # 검색 결과 수
  SEARCH_TOP_K: "5"
  
  # 문서 처리 제한 설정
  MAX_PAGES_TO_PROCESS: "50"
  
  # 파일 경로 (K8s에서는 볼륨 마운트 경로)
  OUTPUT_DIR: "/app/extracted_image" 