apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-backend-config
data:
  # Development environment specific settings
  LLM_PROVIDER: "azure_openai"
  AZURE_OPENAI_ENDPOINT: "https://dev-resource.openai.azure.com/"
  AZURE_OPENAI_DEPLOYMENT_NAME: "dev-gpt-4-mini"
  AZURE_OPENAI_API_VERSION: "2024-12-01-preview"
  
  # Development database settings
  DATABASE_HOST: "dev-postgres-service"
  DATABASE_NAME: "chat_db_dev"
  
  # Development Redis settings
  REDIS_HOST: "dev-redis-service"
