apiVersion: v1
kind: Service
metadata:
  name: ai_backend-service
  namespace: default
  labels:
    app: ai_backend
    environment: development
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: ai_backend
    environment: development
---
# NodePort service for external access in development
apiVersion: v1
kind: Service
metadata:
  name: ai_backend-nodeport
  namespace: default
  labels:
    app: ai_backend
    environment: development
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: ai_backend
    environment: development
