apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-backend-pv
  labels:
    app: ai-backend
    component: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ai-backend-storage
  hostPath:
    path: /data/ai-backend
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-backend-pvc
  namespace: default
  labels:
    app: ai-backend
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ai-backend-storage
