apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ai-backend-development

# Base configuration 참조
resources:
  - ../../

# Namespace 설정
namespace: development

# 개발 환경용 라벨 추가
commonLabels:
  environment: development
  tier: dev

# 개발 환경용 설정
patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

# 이미지 태그 설정
images:
  - name: ai-backend
    newTag: dev-latest

# 레플리카 수 (개발 환경은 1개)
replicas:
  - name: ai-backend-deployment
    count: 1

# 개발 환경용 ConfigMap 생성
configMapGenerator:
  - name: ai-backend-config-dev
    literals:
      - APP_DEBUG=true
      - APP_LOG_LEVEL=debug
      - SERVER_RELOAD=true
      - LOG_TO_FILE=true
